artifacts_root: artifacts


data_ingestion:
  root_dir: articats/data_ingestion
  source_URL: https://drive.google.com/file/d/16Cr8Eg60Sth-uY8RKm6gJZxJlD6h_C6M/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion